// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitalTemp.Infrastructure.Data;

#nullable disable

namespace VitalTemp.Infrastructure.Migrations
{
    [DbContext(typeof(VitalTempDbContext))]
    [Migration("20260827000000_AddHamzaNormalizedFields")]
    partial class AddHamzaNormalizedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("VitalTemp.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("CompositeRiskScore")
                        .HasColumnType("REAL")
                        .HasColumnName("composite_risk_score");

                    b.Property<double>("Correlation")
                        .HasColumnType("REAL")
                        .HasColumnName("correlation");

                    b.Property<string>("HealthIndicator")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("health_indicator");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<double>("PValue")
                        .HasColumnType("REAL")
                        .HasColumnName("p_value");

                    b.Property<double>("TempAvgF")
                        .HasColumnType("REAL")
                        .HasColumnName("temp_avg_f");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("analysis_results", (string)null);
                });

            modelBuilder.Entity("VitalTemp.Domain.Entities.HealthData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("indicator");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_id");

                    b.Property<double?>("NormalizedValue")
                        .HasColumnType("REAL")
                        .HasColumnName("normalized_value");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("health_data", (string)null);
                });

            modelBuilder.Entity("VitalTemp.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("VitalTemp.Domain.Entities.TemperatureReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("Granularity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("granularity");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_id");

                    b.Property<double>("TempC")
                        .HasColumnType("REAL")
                        .HasColumnName("temp_c");

                    b.Property<double>("TempF")
                        .HasColumnType("REAL")
                        .HasColumnName("temp_f");

                    b.Property<double?>("TempNormalized")
                        .HasColumnType("REAL")
                        .HasColumnName("temp_normalized");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("temperature_readings", (string)null);
                });

            modelBuilder.Entity("VitalTemp.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("VitalTemp.Domain.Entities.Location", "Location")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("VitalTemp.Domain.Entities.HealthData", b =>
                {
                    b.HasOne("VitalTemp.Domain.Entities.Location", "Location")
                        .WithMany("HealthDataRecords")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("VitalTemp.Domain.Entities.TemperatureReading", b =>
                {
                    b.HasOne("VitalTemp.Domain.Entities.Location", "Location")
                        .WithMany("TemperatureReadings")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("VitalTemp.Domain.Entities.Location", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("HealthDataRecords");

                    b.Navigation("TemperatureReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
